server:
  port: 9091

spring:
  application:
    name: authentication-service
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_app
    username: root
    password: root
    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


logging:
  level:
    root: INFO

  file:
    path: "./logs/${spring.application.name}"
    name: ${logging.file.path}/authentication-service.log
