server:
  port: 9092
spring:
  application:
    name: notification-service
  output:
    ansi:
      enabled: always

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

spcloud:
  mail:
    queue:
      name: shopping.user-registration.notification
    exchange:
      name: shopping.user-registration.notification
    company: "shopping@gmail.com"

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: INFO
  file:
    path: './logs/${spring.application.name}'
    name: '${logging.file.path}/notification-service.log'