spring:
  application:
    name: authentication-service
  security:
    jwt:
      secret-key: 9ln6jZ1h5BuP28k5RmlOaeL5rise7xe9czd4yA8pZdfGA36zbmRt
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  config:
    profile: native
    import: configserver:http://localhost:8888
